-- Generated by scripts/seed/upload-images.mjs. Do not edit by hand.
-- Points seeded content at placeholder photos uploaded to Cloudinary. Rows are
-- matched to images in a fixed order, cycling when there are more rows than photos.

with images as (select array[
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355092/gcs-seed/announcements/announcement-01.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355093/gcs-seed/announcements/announcement-02.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355094/gcs-seed/announcements/announcement-03.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355095/gcs-seed/announcements/announcement-04.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355097/gcs-seed/announcements/announcement-05.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355098/gcs-seed/announcements/announcement-06.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355099/gcs-seed/announcements/announcement-07.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355101/gcs-seed/announcements/announcement-08.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355102/gcs-seed/announcements/announcement-09.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355103/gcs-seed/announcements/announcement-10.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355104/gcs-seed/announcements/announcement-11.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355106/gcs-seed/announcements/announcement-12.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355107/gcs-seed/announcements/announcement-13.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355109/gcs-seed/announcements/announcement-14.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355110/gcs-seed/announcements/announcement-15.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355111/gcs-seed/announcements/announcement-16.jpg'
  ] as urls),
ranked as (select id, row_number() over (order by start_date) as n from public.announcement)
update public.announcement t
set announcement_image = images.urls[1 + ((ranked.n - 1) % array_length(images.urls, 1))]
from ranked, images
where t.id = ranked.id and t.announcement_image = '';

with images as (select array[
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355112/gcs-seed/articles/article-01.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355114/gcs-seed/articles/article-02.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355115/gcs-seed/articles/article-03.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355116/gcs-seed/articles/article-04.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355117/gcs-seed/articles/article-05.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355119/gcs-seed/articles/article-06.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355121/gcs-seed/articles/article-07.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355122/gcs-seed/articles/article-08.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355123/gcs-seed/articles/article-09.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355124/gcs-seed/articles/article-10.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355126/gcs-seed/articles/article-11.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355127/gcs-seed/articles/article-12.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355128/gcs-seed/articles/article-13.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355129/gcs-seed/articles/article-14.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355130/gcs-seed/articles/article-15.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355131/gcs-seed/articles/article-16.jpg'
  ] as urls),
ranked as (select id, row_number() over (order by added_at desc) as n from public.article)
update public.article t
set article_image = images.urls[1 + ((ranked.n - 1) % array_length(images.urls, 1))]
from ranked, images
where t.id = ranked.id and t.article_image = '';

with images as (select array[
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355132/gcs-seed/playlists/playlist-01.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355134/gcs-seed/playlists/playlist-02.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355135/gcs-seed/playlists/playlist-03.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355136/gcs-seed/playlists/playlist-04.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355138/gcs-seed/playlists/playlist-05.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355139/gcs-seed/playlists/playlist-06.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355140/gcs-seed/playlists/playlist-07.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355141/gcs-seed/playlists/playlist-08.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355143/gcs-seed/playlists/playlist-09.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355144/gcs-seed/playlists/playlist-10.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355146/gcs-seed/playlists/playlist-11.jpg',
    'https://res.cloudinary.com/dch6eenk5/image/upload/v1789355147/gcs-seed/playlists/playlist-12.jpg'
  ] as urls),
ranked as (select id, row_number() over (order by title) as n from public.playlist)
update public.playlist t
set image = images.urls[1 + ((ranked.n - 1) % array_length(images.urls, 1))]
from ranked, images
where t.id = ranked.id and t.image = '';
