// Uploads the downloaded placeholder photos to Cloudinary and writes
// supabase/seeds/25_images.sql, which points the seeded content at them.
//
// Idempotent: public ids are fixed and overwrite is off, so re-running only uploads
// what is missing. Run after download-images.mjs:
//   node scripts/seed/upload-images.mjs
import { readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { v2 as cloudinary } from "cloudinary";
import { loadEnv, requireEnv } from "../lib/load-env.mjs";

loadEnv();
const env = requireEnv(
  "NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
);

cloudinary.config({
  cloud_name: env.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME,
  api_key: env.CLOUDINARY_API_KEY,
  api_secret: env.CLOUDINARY_API_SECRET,
  secure: true,
});

const here = path.dirname(fileURLToPath(import.meta.url));
const imagesDir = path.join(here, "images");
const seedFile = path.resolve(here, "../../supabase/seeds/25_images.sql");

// Which table and column each folder fills, and the order rows are matched in.
const TARGETS = {
  announcements: {
    table: "announcement",
    column: "announcement_image",
    order: "start_date",
  },
  articles: {
    table: "article",
    column: "article_image",
    order: "added_at desc",
  },
  playlists: { table: "playlist", column: "image", order: "title" },
};

const sql = [
  "-- Generated by scripts/seed/upload-images.mjs. Do not edit by hand.",
  "-- Points seeded content at placeholder photos uploaded to Cloudinary. Rows are",
  "-- matched to images in a fixed order, cycling when there are more rows than photos.",
  "",
];

for (const [folder, target] of Object.entries(TARGETS)) {
  const files = (await readdir(path.join(imagesDir, folder)))
    .filter((f) => f.endsWith(".jpg"))
    .sort();

  const urls = [];
  for (const file of files) {
    const publicId = `steady-seed/${folder}/${path.parse(file).name}`;
    const result = await cloudinary.uploader.upload(
      path.join(imagesDir, folder, file),
      {
        public_id: publicId,
        overwrite: false,
        resource_type: "image",
      },
    );
    urls.push(result.secure_url);
    console.log(`${publicId} -> ${result.secure_url}`);
  }

  const list = urls.map((u) => `'${u}'`).join(",\n    ");
  sql.push(
    `with images as (select array[\n    ${list}\n  ] as urls),`,
    `ranked as (select id, row_number() over (order by ${target.order}) as n from public.${target.table})`,
    `update public.${target.table} t`,
    `set ${target.column} = images.urls[1 + ((ranked.n - 1) % array_length(images.urls, 1))]`,
    `from ranked, images`,
    `where t.id = ranked.id and t.${target.column} = '';`,
    "",
  );
}

await writeFile(seedFile, sql.join("\n"));
console.log(`wrote ${path.relative(process.cwd(), seedFile)}`);
