name: GCS Management System and Landing Page Production Deployment

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  lint:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Run Prettier
        run: pnpm format -- --check

  type-check:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: pnpm install

      - name: Run TypeScript Type Checking
        run: pnpm type-check
